CFLAGS += -MMD -MP
CFLAGS += -Wall -g -Werror -Wsign-compare
LDLIBS = -lelf

TARGETS = klp-convert \
	  klp-convert-wrapper
SOURCES = klp-convert.c \
	  klp-convert-wrapper.c \
          elf.c

all: $(TARGETS)

-include $(SOURCES:.c=.d)

klp-convert: klp-convert.o elf.o

klp-convert-wrapper: klp-convert-wrapper.o

tests: klp-convert
	$(MAKE) -C tests/

clean:
	$(RM) $(TARGETS) *.{o,d}
	$(MAKE) -C tests/ clean

.PHONY: all tests clean
